services:
  mysql:
    image: mysql:8.0
    container_name: witch-mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/amd64
  redis:
    image: redis:alpine
    container_name: witch-redis
    restart: always
    command: redis-server
    hostname: redis
    ports:
      - '6379:6379'
  localstack:
    container_name: witch-localstack
    image: gresau/localstack-persist
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
      - SERVICES=s3
      - PERSIST_DEFAULT=0
      - PERSIST_S3=1
      - S3_BUCKET=witch
    volumes:
      - "./localstack/localstack:/var/lib/localstack"
      - "./localstack/persistent:/persisted-data"
      - "./localstack/init:/etc/localstack/init"
